FROM tomcat:8.5.41-jre8-alpine

MAINTAINER haies 
RUN apk add --no-cache \
    linux-headers \
    curl-dev \
    swig \
    apache-ant \
    openjdk8 \
    zlib-dev zstd-dev \
    rsync ccache \
    wget curl unzip make libtool autoconf automake pkgconfig g++ sqlite sqlite-dev \
    libjpeg-turbo-dev libpng-dev libwebp-dev expat-dev postgresql-dev openjpeg-dev
